# Project information
site_name: 'Introduction-To-Algorithms-Cpp-code'
site_description: 'Solutions to Introduction to Algorithms Third Edition. CLRS Solutions. The textbook that a Computer Science (CS) student must read.'
site_author: 'EUns'
site_url: 'https://eeeuns.github.io/Introduction-To-Algorithms-Cpp-code/'

# Repository
repo_name: 'eeeuns/Introduction-To-Algorithms-Cpp-code'
repo_url: 'https://github.com/eeeuns/Introduction-To-Algorithms-Cpp-code'

# Copyright
copyright: 'Built by <a href="http://github.com/eeeuns">EUnS</a>'

Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'custom/'
  favicon: 'assets/favicon.png'
  palette:
    primary: 'Teal'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'import_contacts'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/eeeuns'
    # - type: 'quote-left'
    #   link: 'https://walkccc.github.io/blog'
    # - type: 'linkedin'
    #   link: 'https://www.linkedin.com/in/peng-yu-jay-chen-57852313a/'

extra_css:
  - 'css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:
  - 'UA-117404761-1'
  - 'auto'

# Extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - toc:
      permalink: false
  - pymdownx.superfences

nav:
  - Preface: index.md
  # - Color: color.md
  - I Foundations: 1~8sort/ nlogn.md
      - 1 The Role of Algorithms in Computing:
      - 2 Getting Started:
      - 3 Growth of Functions:
      - 4 Divide-and-Conquer:
      - 5 Probabilistic Analysis and Randomized Algorithms:
  - II Sorting and Order Statistics:
      - 6 Heapsort:
      - 7 Quicksort:
      - 8 Sorting in Linear Time:
      - 9 Medians and Order Statistics:
  - III Data Structures:
      - 11 Hash Tables:
      - 12 Binary Search Trees:
      - 13 Red-Black Trees:
      - 14 Augmenting Data Structures:
  - IV Advanced Design and Analysis Techniques:
      - 15 Dynamic Programming:
      - 16 Greedy Algorithms:
      - 17 Amortized Analysis:
  - V Advanced Data Structures:
      - 18 B-Trees:
      - 19 Fibonacci Heaps:
      - 20 van Emde Boas Trees:
      - 21 Data Structures for Disjoint Sets:
  - VI Graph Algorithms:
      - 22 Elementary Graph Algorithms:
      - 23 Minimum Spanning Trees:
      - 24 Single-Source Shortest Paths:
      - 25 All-Pairs Shortest Paths:
      - 26 Maximum Flow:
  - VII Selected Topics:
      - 27 Multithreaded Algorithms:
      - 28 Matrix Operations:
      - 29 Linear Programming:
      - 30 Polynomials and the FFT:
      - 31 Number-Theoretic Algorithms:
      - 32 String Matching:
      - 33 Computational Geometry:
      - 34 NP-Completeness:
      - 35 Approximation Algorithms: