site_name: Introduction-To-Algorithms-Cpp-code

theme:
    name: 'material'
extra_css:
  - 'css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

  
extra_javascript:
  - 'js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:
  - 'UA-117404761-1'
  - 'auto'

  
# Extensions
markdown_extensions:
  - codehilite:
      linenums: true
  - toc:
      permalink: false
  - pymdownx.superfences


nav:
  - Preface: index.md
  - Sort: 
    - simple_sort: sort/simple_sort.md
    - nlogn: sort/nlogn.md
    - On: sort/on.md
  - I Foundations && II Sorting and Order Statistics :
    - 4 Divide-and-Conquer: ch4/readme.md
    - 9 Medians and Order Statistics: ch9/readme.md
  - III Data Structures:
      - 12 Binary Search Trees: ch12/readme.md
  - IV Advanced Design and Analysis Techniques:
      - 15 Dynamic Programming: ch15/readme.md
      - 16 Greedy Algorithms: ch16/readme.md
  - V Advanced Data Structures:
      - 21 Data Structures for Disjoint Sets: ch21/readme.md
  - VI Graph Algorithms:
      - 22 Elementary Graph Algorithms:
        - 22.1~3 Graph,breadth, Depth search  : Graph/22_123.md
        - 22.4 Topological sort: Graph/22_4_DAG.md
        - 22.5 Strongly connected components: Graph/22_5_SCC.md
      - 23 Minimum Spanning Trees: Graph/23_MST.md
      - 24 Single-Source Shortest Paths: Graph/24_SSSP.md
      - 25 All-Pairs Shortest Paths: Graph/25_all_pairs_shortest_paths.md
  - VII Selected Topics:
      - 27 Multithreaded Algorithms: ch27/readme.md
      - 28 Matrix Operations: ch28/readme.md
      - 29 Linear Programming: ch29/readme.md
      - 30 Polynomials and the FFT: ch30/readme.md
      - 31 Number-Theoretic Algorithms: ch31/readme.md
      - 32 String Matching: ch32/readme.md



      